language: python
python: 3.5
install:
  - sudo add-apt-repository ppa:fontforge/fontforge -y
  - sudo apt-get update -qq
  - sudo apt-get install fontforge
script:
  - make
notifications:
  webhooks: http://webhook.hakatashi.com/travis
