dist: bionic
addons:
  apt:
    sources:
      # for some reason python3-fontforge is only available in focal
      - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted
      - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ focal universe
    packages:
      - python3
      - python3-fontforge
      - python3-jinja2
      - python3-fonttools
script:
  - make
deploy:
  provider: releases
  api_key:
    secure: Bo8AlrlQdj4Z8KIu4TKg05HQznAdFdG2uSpe3Hg9jdsSR1AFRHcVsLhs8GNENTykNg66q7gZZJkPlLd0CPLD6dQ1seDqvllMpcBYiNIboeo5rAQ2Y92Q+aWGUZVblhsl+2WEQOyPEYzOFLbGrVKWjZsX2z0s9k14Sn+aRNlAD8fKVeZQzQtNpBiOZzdjkBUYyjwz+Hl+DV4jRpKJtyQ/g/DaSPLrZ3lzqkW1ANPcBTfBZrj5Qfb/FRydJ2FLlwpP3Rbq0zlW1ATKP9qtxXMvyowQtMxjWiHtwW31wLWhjvQBEisjZBgBvUhbZsKxAObgKOneNoxKOFXv2LmX75qwdOROMttlSDgmn9H48WNWJ/VBFOePLtYQjGTlsDXI7iTmDTAEDSsjA+ZGv4K6QX8J9sAUnRnl31SQIaioyfw3VBkNkp8oc6kvmPB+SLIsyjazKlkBc5Ye8qnA7QiB0MlXcpXS3Tv87MgAmdvLoixL3Mh3sIEsgC9sSB78WQjS1sHRrTHigAAoHEuRKM09CsNQ3MlyfCD7DXFWYDF9IlbsoK3QncWyIvBtdMlS9qbGM17/8LohYNKxU8XsOS/EGXgnMLkYyDn/IUQ3bUzFERBVSf4OUgkPVyeTcJDfmmWD6ZWFcsy2wAKlyJKjmPGv6IxD+PjQGtdhk8gDkVvncGeGBz8=
  file:
    - RictyDiminished-with-FiraCode-Regular.ttf
    - RictyDiminished-with-FiraCode-Bold.ttf
    - RictyDiminishedDiscord-with-FiraCode-Regular.ttf
    - RictyDiminishedDiscord-with-FiraCode-Bold.ttf
  skip_cleanup: true
  on:
    tags: true
    repo: hakatashi/RictyDiminished-with-FiraCode
notifications:
  webhooks: http://webhook.hakatashi.com/travis
