language: python
python: 3.5
sudo: required
install:
  - sudo add-apt-repository ppa:fontforge/fontforge -y
  - sudo apt-get update -qq
  - sudo apt-get install fontforge
  - pip install -r requirements.txt
script:
  - make
notifications:
  webhooks: http://webhook.hakatashi.com/travis
